name: Enforce PRs targeting develop

on:
    pull_request:
        branches: [main]

jobs:
    check-source-branch:
        runs-on: ubuntu-latest
    steps:
        - name: Fail if PR targets main
          run: |
              if [[ "${{ github.head_ref }}" != "develop" ]]; then
                  echo "Pull requests to 'main' are not allowed. Please target 'develop' instead."
                  exit 1
              fi
